---
title: "Article de validation - Structure"
author: "Nicolas Bressoud"
date: "généré le 19 décembre 2020"
output: 
  bookdown::word_document2:
    citation_package: none
    reference_docx: "template/article_2_template.docx"
    toc: false
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        "output/","article_2_", format(Sys.time(), '%Y%m%d'), '.docx'
      ),
      envir = globalenv()
    )
  })
---

# Auteurs (ordre à déterminer rapidement)
Nicolas Bressoud, Rebecca Shankland, Philippe Gay, Andrea C. Samson, Philippe Dubreuil, Karel Belleville, Jacques Forest

Je me base sur la structure du travail de Bernet, Karsenti, & Roy (2014) qui ont traduit et validé la SEM en français.

# Origine des données 

Banque de données CRHA :
Dubreuil, P., Forest, J., & Courcy, F. (2014). From strengths use to work performance: The role of harmonious passion, subjective vitality and concentration. The Journal of Positive Psychology, 9, 335-349.
 
Banque de données corrigée CRE :
Dubreuil, P., Forest, J., Gillet, N., Fernet, C., Thibault-Landry, A., Crevier-Braud, L., & Girouard, S. (2016). Facilitating well-being and performance through the development of strengths at work: Results from an intervention program. International Journal of Applied Positive Psychology, 1(1), 1-19.
 
Banque de données de Karel Belleville :
Belleville, K., Dubreuil, P., & Courcy, F. (2019). The Use of Workplace Strengths and Proactive and Organizational Citizenship Behaviours: An Examination of the Mediating Role of Well-Being. Canadian Journal of Administrative Sciences, 37(2), 135-148.
 
Banque de données CRDICA :
Données provenant de l’échantillon #2 de ma thèse, celles-ci n’ont jamais été utilisées
 
Banque de données éducation T1 :
Données de projet non publié
 
Banque de données HUMAN RELATIONS :
Forest, J., Mageau, G. A., Crevier-Braud, L., Dubreuil, P., Bergeron, E., & Lavigne, G. L. (2012). Harmonious passion as a mediator of the relation between signature strengths’ use and optimal functioning at work: Test of an intervention program. Human Relations, 65, 1233-1252.



# Introduction 
0.5 à 1 page
importance du problème, etc

# Cadre théorique
1 à 2 pages
historique, modèle, focus, description
conclure par intention de l'article (dont échelle courte? échelle adaptée aux enfants?).

# Méthode

## Participants
description

## Version originale du questionnaire
source, validation d'origine

## Méthodologie de validation 
choix théorique sourcé, traduction.
Bernet parlait de Vallerand et ses 7 étapes... (1) la préparation d’une version préliminaire, (2) l’évaluation et la modification de cette première version, (3) l’évaluation de la version expérimentale par un prétest, (4) l’évaluation de la validité concomitante et de contenu, (5) l’évaluation de la fidélité, (6) l’évaluation de la validité de construit, et (7) l’établissement de normes.

### version préliminaire
raconter comment on a traduit. Selon quelle méthode de traduction.

### évaluation et modification de la première version
rétrotraduction. A fusionner avec étape ci-dessus.

### DONE??? évaluation de la version expérimentale par un prétest
l’évaluation de la clarté des énoncés par des membres de la population cible par un prétest.


# Résultats
indiquer nos critères pour décider ceci ou cela.
Alphas de cronbach
tableau de l'AFE (Items, facteurs de corrélation, communauté, ...)
corrélations entre les différentes dimensions (par nécessaire chez nous)




### DONE??? évaluation de la validité concomitante et de contenu
non. Pas pertinent.

### évaluation de la fidélité
Quand a-t-on soumis et à qui ? (précisions par rapport au point "participants").
Alpha de Cronbach (oui)
stabilité temporalle entre les différents moments de saisie des données (non)

### évaluation de la validité de construit
Cette vérification se réalise à trois niveaux :

- niveau de la structure du construit lui-même : AFE
- niveau des relations entre les différents construits inhérents à la structure théorique
- conséquences et corrélats du ou des construits

Attention, dès p.25, Bernet et al. justifie chaque choix stat en montrant les controverses... Aie. 

Comment justifier nos choix ?

Indice KMO et test de sphéricité de Bartlett
matrice de corrélation
tracé d'effondrement.
ACP

? AFC?

### établissement de normes?

###proposer une version courte? 
environ 6 ou 7 items car plus "rentable", choix selon les items plus discriminants (quanti et quali)....
? esk inverser qqs items ?







# Discussion
texte court

## limites
méthodo etc.

## perspectives
a faire pour consolider.

# Références

